name: Release

on:
  push:
    tags:
      - '**'

jobs:
  build:
    name: Create a release
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Create release
        uses: crazy-max/ghaction-github-release@v2
        with:
          token: ${{ secrets.RELEASE_TOKEN }}
          draft: true
          prerelease: false
