name: Extension Tests

on:
  schedule:
    - cron: '0 0 * * *'
  pull_request:
  push:

jobs:
  extension-tests:
    name: PHPUnit Extension Tests [PHP ${{ matrix.php-version }}]
    runs-on: ubuntu-20.04

    strategy:
      matrix:
        php-version:
          - '8.1'
          - '8.2'

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php-version }}
          coverage: xdebug

      - name: Get composer cache directory
        id: composer-cache
        run: echo "COMPOSER_CACHE_FILES_DIR=$(composer config cache-files-dir)" >> $GITHUB_OUTPUT

      - name: Cache composer dependencies
        uses: actions/cache@v3
        with:
          path: ${{ steps.composer-cache.outputs.COMPOSER_CACHE_FILES_DIR }}
          key: composer-${{ matrix.php-version }}-${{ hashFiles('**/composer.*') }}
          restore-keys: |
            composer-${{ matrix.php-version }}-
            composer-

      - name: Setup Composer's GitHub OAuth access
        run: composer config --global github-oauth.github.com ${{ secrets.GITHUB_TOKEN }}

      - name: Install dependencies
        run: composer update --ansi

      - name: Run Extension Tests
        run: vendor/bin/phpunit

      - name: Upload coverage results to Coveralls
        run: |
          composer global require --ansi php-coveralls/php-coveralls
          php-coveralls --verbose --coverage_clover=build/phpunit/logs/clover.xml --json_path=build/phpunit/logs/coverage-upload.json
        env:
          COVERALLS_REPO_TOKEN: ${{ secrets.COVERALLS_REPO_TOKEN }}
          COVERALLS_PARALLEL: true
          COVERALLS_FLAG_NAME: PHP ${{ matrix.php-version }}

  coveralls-upload:
    name: Trigger parallel build webhook on Coveralls
    runs-on: ubuntu-20.04
    needs:
      - extension-tests

    steps:
      - name: Upload to Coveralls API
        uses: coverallsapp/github-action@master
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          parallel-finished: true
